export const CONFIG = {
  GAME: {
    TITLE: 'Hearth & Harvest',
    VERSION: '0.1.0',
    TARGET_FPS: 60,
    LANDSCAPE_ONLY: true,
  },
  WORLD: {
    GRAVITY: -25,
    TERRAIN_SIZE: 200,
    TERRAIN_SEGMENTS: 64,
    WATER_LEVEL: 0.5,
    DAY_CYCLE_MINUTES: 15,
    SEASON_DAYS: 7,
  },
  PLAYER: {
    HEIGHT: 1.8,
    RADIUS: 0.4,
    SPEED: 5,
    SPRINT_MULT: 1.8,
    JUMP_FORCE: 8,
    STAMINA_MAX: 100,
    STAMINA_REGEN: 20,
    HEALTH_MAX: 100,
    HUNGER_MAX: 100,
    THIRST_MAX: 100,
    ENERGY_MAX: 100,
    WARMTH_MAX: 100,
  },
  COMBAT: {
    LIGHT_ATTACK_DAMAGE: 15,
    HEAVY_ATTACK_DAMAGE: 35,
    LIGHT_STAMINA_COST: 10,
    HEAVY_STAMINA_COST: 25,
    BLOCK_STAMINA_DRAIN: 15,
    DODGE_STAMINA_COST: 20,
    PERFECT_BLOCK_WINDOW: 0.2,
    STAGGER_THRESHOLD: 3,
    HITSTOP_MS: 80,
    LOCK_ON_RANGE: 20,
    COMBO_WINDOW: 0.8,
    ARROW_SPEED: 30,
    BOW_DRAW_TIME: 0.5,
  },
  ZONES: {
    VILLAGE:    { id: 'village',    name: 'Village Hub',    color: 0x8B5E3C, terrainColor: [0.45,0.35,0.2], fog: 0xBBAA88, ambient: 0x443322, guardians: 0 },
    FOREST:     { id: 'forest',     name: 'Forest',         color: 0x2D5A27, terrainColor: [0.25,0.5,0.2], fog: 0x88AA77, ambient: 0x1A3A15, guardians: 0 },
    RIVERLANDS: { id: 'riverlands', name: 'Riverlands',     color: 0x4A7C59, terrainColor: [0.3,0.6,0.3], fog: 0x99BBAA, ambient: 0x2A4A35, guardians: 0 },
    FARMLANDS:  { id: 'farmlands',  name: 'Farmlands',      color: 0x7A9A4A, terrainColor: [0.45,0.55,0.25], fog: 0xCCBB88, ambient: 0x4A6A2A, guardians: 0 },
    MINE:       { id: 'mine',       name: 'Iron Mine',      color: 0x4A3A2A, terrainColor: [0.3,0.25,0.2], fog: 0x332211, ambient: 0x1A0A0A, guardians: 1 },
    BANDIT_CAMP:{ id: 'banditcamp', name: 'Bandit Camp',    color: 0x5A2A2A, terrainColor: [0.35,0.2,0.15], fog: 0x442222, ambient: 0x2A0A0A, guardians: 2 },
    RUINS:      { id: 'ruins',      name: 'Old Ruins',      color: 0x6A5A4A, terrainColor: [0.4,0.35,0.3], fog: 0x554433, ambient: 0x3A2A1A, guardians: 3 },
  },
  ZONE_GATES: [
    { from: 'village',    to: 'forest',     x: 80, z: 0,  destX: -75, destZ: 0 },
    { from: 'village',    to: 'riverlands', x: 0,  z: 80, destX: 0,  destZ: -75 },
    { from: 'village',    to: 'farmlands',  x: -80, z: 0,  destX: 75, destZ: 0 },
    { from: 'forest',     to: 'mine',       x: -80, z: 0,  destX: 75, destZ: 0 },
    { from: 'riverlands', to: 'banditcamp', x: 0,  z: -80, destX: 0,  destZ: 75 },
    { from: 'farmlands',  to: 'ruins',      x: 80, z: 0,  destX: -75, destZ: 0 },
  ],
  GRAPHICS: {
    QUALITY_TIERS: ['potato', 'low', 'medium', 'high', 'ultra'],
    DEFAULT_TIER: 'medium',
  },
  TOOLS: {
    AXE: { name: 'Axe', durability: 200, damage: 20, tier: 1 },
    HOE: { name: 'Hoe', durability: 150, damage: 5, tier: 1 },
    SCYTHE: { name: 'Scythe', durability: 150, damage: 15, tier: 1 },
    PICKAXE: { name: 'Pickaxe', durability: 200, damage: 18, tier: 1 },
    FISHING_ROD: { name: 'Fishing Rod', durability: 100, damage: 0, tier: 1 },
    KNIFE: { name: 'Knife', durability: 100, damage: 10, tier: 1 },
    HAMMER: { name: 'Hammer', durability: 200, damage: 12, tier: 1 },
    BUCKET: { name: 'Bucket', durability: 100, damage: 2, tier: 1 },
  },
  CROPS: {
    WHEAT: { name: 'Wheat', growTime: 300, seasons: ['spring', 'summer'] },
    BARLEY: { name: 'Barley', growTime: 280, seasons: ['spring', 'summer'] },
    CABBAGE: { name: 'Cabbage', growTime: 240, seasons: ['spring', 'autumn'] },
    CARROT: { name: 'Carrot', growTime: 200, seasons: ['spring', 'summer', 'autumn'] },
    FLAX: { name: 'Flax', growTime: 260, seasons: ['spring'] },
    ONION: { name: 'Onion', growTime: 220, seasons: ['spring', 'autumn'] },
  },
  FARMING: {
    PLOT_RADIUS: 0.6,
    WATER_CAPACITY: 3,
    BASE_GROWTH_RATE: 0.2,
    WATER_BONUS: 1.5,
    FERT_BONUS: 1.3,
    SEASON_PENALTY: 0.2,
    SEED_DROP_CHANCE: 0.3,
    HARVEST_AMOUNT: 2,
  },
  CRAFTING_STATIONS: {
    CAMPFIRE:   { id: 'campfire',   name: 'Campfire',   description: 'Cook raw food and bake bread' },
    HEARTH:     { id: 'hearth',     name: 'Hearth',     description: 'Bake pies and brew ale' },
    WORKBENCH:  { id: 'workbench',  name: 'Workbench',  description: 'Craft tools and weapons' },
    ANVIL:      { id: 'anvil',      name: 'Anvil',      description: 'Forge metal gear and repair' },
    SAWMILL:    { id: 'sawmill',    name: 'Sawmill',    description: 'Process wood more efficiently' },
    LOOM:       { id: 'loom',       name: 'Loom',       description: 'Weave cloth and leather armor' },
    KILN:       { id: 'kiln',       name: 'Kiln',       description: 'Fire clay into bricks' },
    STILL:      { id: 'still',      name: 'Still',      description: 'Brew ale from barley' },
  },
};
