export const CONFIG = {
  GAME: {
    TITLE: 'Hearth & Harvest',
    VERSION: '0.1.0',
    TARGET_FPS: 60,
    LANDSCAPE_ONLY: true,
  },
  WORLD: {
    GRAVITY: -25,
    TERRAIN_SIZE: 500,
    TERRAIN_SEGMENTS: 128,
    WATER_LEVEL: 0.5,
    DAY_CYCLE_MINUTES: 15,
    SEASON_DAYS: 7,
  },
  PLAYER: {
    HEIGHT: 1.8,
    RADIUS: 0.4,
    SPEED: 5,
    SPRINT_MULT: 1.8,
    JUMP_FORCE: 8,
    STAMINA_MAX: 100,
    STAMINA_REGEN: 20,
    HEALTH_MAX: 100,
    HUNGER_MAX: 100,
    THIRST_MAX: 100,
    ENERGY_MAX: 100,
    WARMTH_MAX: 100,
  },
  COMBAT: {
    LIGHT_ATTACK_DAMAGE: 15,
    HEAVY_ATTACK_DAMAGE: 35,
    LIGHT_STAMINA_COST: 10,
    HEAVY_STAMINA_COST: 25,
    BLOCK_STAMINA_DRAIN: 15,
    DODGE_STAMINA_COST: 20,
    PERFECT_BLOCK_WINDOW: 0.2,
    STAGGER_THRESHOLD: 3,
    HITSTOP_MS: 80,
    LOCK_ON_RANGE: 20,
    COMBO_WINDOW: 0.8,
  },
  ZONES: {
    VILLAGE: { name: 'Village Hub', color: 0x8B5E3C, ambient: 0x443322 },
    FOREST: { name: 'Forest', color: 0x2D5A27, ambient: 0x1A3A15 },
    RIVERLANDS: { name: 'Riverlands', color: 0x4A7C59, ambient: 0x2A4A35 },
    FARMLANDS: { name: 'Farmlands', color: 0x7A9A4A, ambient: 0x4A6A2A },
    MINE: { name: 'Iron Mine', color: 0x4A3A2A, ambient: 0x1A0A0A },
    BANDIT_CAMP: { name: 'Bandit Camp', color: 0x5A2A2A, ambient: 0x2A0A0A },
    RUINS: { name: 'Old Ruins', color: 0x6A5A4A, ambient: 0x3A2A1A },
  },
  GRAPHICS: {
    QUALITY_TIERS: ['potato', 'low', 'medium', 'high', 'ultra'],
    DEFAULT_TIER: 'medium',
  },
  TOOLS: {
    AXE: { name: 'Axe', durability: 200, damage: 20, tier: 1 },
    HOE: { name: 'Hoe', durability: 150, damage: 5, tier: 1 },
    SCYTHE: { name: 'Scythe', durability: 150, damage: 15, tier: 1 },
    PICKAXE: { name: 'Pickaxe', durability: 200, damage: 18, tier: 1 },
    FISHING_ROD: { name: 'Fishing Rod', durability: 100, damage: 0, tier: 1 },
    KNIFE: { name: 'Knife', durability: 100, damage: 10, tier: 1 },
    HAMMER: { name: 'Hammer', durability: 200, damage: 12, tier: 1 },
    BUCKET: { name: 'Bucket', durability: 100, damage: 2, tier: 1 },
  },
  CROPS: {
    WHEAT: { name: 'Wheat', growTime: 300, seasons: ['spring', 'summer'] },
    BARLEY: { name: 'Barley', growTime: 280, seasons: ['spring', 'summer'] },
    CABBAGE: { name: 'Cabbage', growTime: 240, seasons: ['spring', 'autumn'] },
    CARROT: { name: 'Carrot', growTime: 200, seasons: ['spring', 'summer', 'autumn'] },
    FLAX: { name: 'Flax', growTime: 260, seasons: ['spring'] },
    ONION: { name: 'Onion', growTime: 220, seasons: ['spring', 'autumn'] },
  },
};
